"""Stage 0: Scaffold the Lean project directories and generate root import file."""

import os
import shutil


LAKEFILE = """name = "formalization_project"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Formalization"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "Formalization"
"""

LEAN_TOOLCHAIN = "leanprover/lean4:v4.29.0-rc1\n"


def scaffold(input_dir: str, project_root: str, chapters: list[int]) -> None:
    """Create the Lean project skeleton."""
    os.makedirs(project_root, exist_ok=True)

    template_files = {
        "lakefile.toml": LAKEFILE,
        "lean-toolchain": LEAN_TOOLCHAIN,
    }
    for fname, content in template_files.items():
        dst = os.path.join(project_root, fname)
        if not os.path.exists(dst):
            with open(dst, "w", encoding="utf-8") as f:
                f.write(content)
        elif fname == "lakefile.toml":
            _ensure_mathlib_dependency(dst)

    # Create directory tree
    dirs = [
        os.path.join(project_root, "Formalization"),
        os.path.join(project_root, "Formalization", "utils"),
        os.path.join(project_root, "natural_language", "raw_data", "theorems_and_defs"),
    ]
    for ch in chapters:
        dirs.append(os.path.join(project_root, "Formalization", "intermediate_files", f"ch{ch}"))
        dirs.append(os.path.join(project_root, "experiments", "auto", f"ch{ch}", "verification"))
        dirs.append(os.path.join(project_root, "experiments", "auto", f"ch{ch}", "verification_fl_statement"))

    for d in dirs:
        os.makedirs(d, exist_ok=True)

    # Copy raw chapter data
    raw_dir = os.path.join(project_root, "natural_language", "raw_data")
    for ch in chapters:
        src = os.path.join(input_dir, f"ch{ch}.txt")
        dst = os.path.join(raw_dir, f"ch{ch}.txt")
        if os.path.exists(src):
            shutil.copy2(src, dst)
        else:
            print(f"WARNING: {src} not found, skipping")

    # Generate Formalization.lean (root import)
    root_lean = os.path.join(project_root, "Formalization.lean")
    lines = [f"import Formalization.ch{ch}" for ch in chapters]
    with open(root_lean, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    # Create placeholder ch*.lean files
    formalization_dir = os.path.join(project_root, "Formalization")
    for ch in chapters:
        ch_lean = os.path.join(formalization_dir, f"ch{ch}.lean")
        if not os.path.exists(ch_lean):
            with open(ch_lean, "w", encoding="utf-8") as f:
                f.write(f"-- Chapter {ch}: placeholder (will be generated by the pipeline)\n")

    print(f"Scaffolded project with chapters {chapters}")


def _ensure_mathlib_dependency(lakefile: str) -> None:
    with open(lakefile, encoding="utf-8") as f:
        content = f.read()
    if 'name = "mathlib"' in content and 'scope = "leanprover-community"' in content:
        return
    marker = 'defaultTargets = ["Formalization"]\n'
    block = """
[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"
"""
    if marker in content:
        content = content.replace(marker, marker + block, 1)
    else:
        content = block + "\n" + content
    with open(lakefile, "w", encoding="utf-8") as f:
        f.write(content)
